version: 2

jobs:
  linux:
    docker:
      - image: swift:4.1
    steps:
      - checkout
      - run:
          name: Update apt
          command: apt-get update
      - run: 
          name: Install Docker
          command: |
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
            add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu trusty stable"
            apt-get update
            apt-get install -y docker-ce
            systemctl status docker
      - run:
          name: Install wrk
          command: |
            apt-get install build-essential libssl-dev git -yq
            git clone https://github.com/wg/wrk.git wrk
            cd wrk
            make
            cp wrk ~/
          working_directory: ~/
      - run: 
          name: Build images
          command: make all
      - run: 
          name: Run benchmarks
          command: ./benchmark.sh
          working_directory: ~/

workflows:
  version: 2
  tests:
    jobs:
      - linux
      # - macos
